edition = "2023";

import "google/protobuf/empty.proto";

package synqueen.v1;

service FolderManagement {
  // List all folders being synchronized
  rpc ListFolders(google.protobuf.Empty) returns (ListFoldersResponse) {}

  // Add the folder to synchronize
  rpc AddFolder(AddFolderRequest) returns (google.protobuf.Empty) {}

  // Remove the folder from synchronization
  rpc RemoveFolder(RemoveFolderRequest) returns (google.protobuf.Empty) {}
}

message ListFoldersResponse {
    repeated Folder folders = 1;
}

message Folder {
    string path = 1;
}

message AddFolderRequest {
    string path = 1;
}

message RemoveFolderRequest {
    string path = 1;
}
